### PR TITLE
Generate changelog and add PR template

### PR DESCRIPTION
**Pull request by JordanMartinez**
Part of purescript/purescript#3984

### CODE REVIEW

**Review by thomashoneyman — APPROVED** [review]

**Comment by thomashoneyman** [comment]
I merged this to verify that nothing is linked when you open a new PR. We don't need the #0000 (could get away with say #00), but it does appear to be fine. Thanks!

**Comment by JordanMartinez** [comment]
Thanks. Let's just keep with #0000 as that's what I've already submitted.

**Comment by milesfrain** [comment]
Looks like changelog wasn't added in this one.

**Comment by JordanMartinez** [comment]
:scream: I'll work on that.

**Comment by JordanMartinez** [comment]
See #32

**Pull request merged**
